version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: "production"
    ports: 
      - "3001:4001"
    environment:
      - NODE_ENV=production
    command: node index.js